---
############## Resources ################
resources:
  - name: ci-docker
    type: docker-image
    source:
      email: ((docker-email))
      password: ((docker-password))
      repository: pcfmetrics/catalyst
      username: ((docker-username))
      tag: ((docker-tag))

############## Jobs ################
jobs:
  - name: push-dora
    serial: true
    plan:
      - in_parallel:
          - get: ci-docker
      - task: push
        image: ci-docker
        config:
          platform: linux
          inputs:
            - name: dora-src
          params:
          run:
            path: bash
            args:
              - -ecx
              - |
                export SYSTEM_DOMAIN=sys.buellton.cf-app.com
                export CF_USERNAME=admin
                export CF_PASSWORD=iX15vNaaWpStQH44-LWXu3Mj3Ge-xX4O
                
                
                cf login -a api.${SYSTEM_DOMAIN} -u ${CF_USERNAME} -p ${CF_PASSWORD} -o system -s system
                for (( ; ; )) do {
                  for i in {26..40}; do {
                  sleep 1
                
                  curl --location --request GET https://custom-metrics-${i}.apps.buellton.cf-app.com/simple &
                  sleep 1
                  curl --location --request GET https://custom-metrics-${i}.apps.buellton.cf-app.com/high_latency &
                  sleep 1
                  curl --location --request GET https://custom-metrics-${i}.apps.buellton.cf-app.com/custom_metric?inc=1 &
                  sleep 1
                  curl --location --request GET https://custom-metrics-${i}.apps.buellton.cf-app.com/custom_metric &
                }; done
                  sleep 50
                }; done


groups:
  - name: app-metrics-add-monitor
    jobs:
      - push-dora
